/* Lua API reference — renders lua-api-data.js, and lazily lua-natives-data.js.
   Both are generated by project-native-gui/tools/update_site_lua_api.py.

   Performance notes (the page must stay instant):
     * search keys are lowercased ONCE per callable, on first use of a source,
       never per keystroke;
     * only one namespace is in the DOM at a time, capped at CHUNK rows with an
       explicit "show all" — NETWORK alone has 834 natives;
     * the 480 KB natives file is only fetched when someone opens that tab;
     * the sidebar is rebuilt only when the filter actually changes, not on
       every keystroke.

   Deep links are #<namespace>.<function>, e.g. /lua#draw.rect  */
(function () {
  'use strict';

  var API = window.NENYOO_LUA_API;
  var side = document.getElementById('luaSide');
  var out = document.getElementById('luaOut');
  var bar = document.getElementById('luaLayers');
  var tabs = document.getElementById('luaTabs');
  var search = document.getElementById('luaSearch');
  var clear = document.getElementById('luaClear');
  var count = document.getElementById('luaCount');
  var src = document.getElementById('luaSrc');

  if (!API || !API.namespaces || !out) {
    if (out) out.innerHTML = '<div class="lua-state">The Lua API list could not be loaded.</div>';
    return;
  }

  var CHUNK = 200;          // rows rendered before "show all"
  var MAX_HITS = 300;       // search results rendered at once
  var NATIVES_URL = 'lua-natives-data.js';

  var state = {
    source: 'api',          // 'api' | 'natives'
    ns: null,
    layer: '',
    q: '',
    expand: false,
    sideKey: ''             // guards needless sidebar rebuilds
  };

  var natives = null;       // filled on first use
  var nativesLoading = false;

  /* ---------- helpers ---------- */

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function layerKey(l) {
    l = (l || '').toLowerCase();
    if (l.indexOf('stand') > -1) return 'stand';
    if (l.indexOf('foundation') > -1) return 'foundation';
    if (l.indexOf('engine') > -1) return 'engine';
    return 'other';
  }

  function model() {
    return state.source === 'natives' ? natives : API;
  }

  /* Lowercase search keys, built once per source. */
  function indexOnce(data) {
    if (!data || data._indexed) return;
    for (var i = 0; i < data.namespaces.length; i++) {
      var n = data.namespaces[i], p = n.ns.toLowerCase() + '.';
      for (var f = 0; f < n.fns.length; f++) {
        var fn = n.fns[f];
        fn._k = (p + fn.n + ' ' + (fn.sig || '') + ' ' +
                 (fn.d || '') + ' ' + (fn.h || '')).toLowerCase();
      }
    }
    data._indexed = true;
  }

  function nsOf(name) {
    var d = model();
    if (!d) return null;
    for (var i = 0; i < d.namespaces.length; i++) {
      if (d.namespaces[i].ns === name) return d.namespaces[i];
    }
    return null;
  }

  function passesLayer(fn) {
    if (state.source === 'natives' || !state.layer) return true;
    return layerKey(fn.l) === state.layer;
  }

  /* ---------- markup ---------- */

  function sigHTML(fn) {
    if (state.source === 'natives') {
      return '<b>' + esc(fn.n) + '</b><s>(' + esc(fn.p || '') + ')</s>';
    }
    var s = fn.sig, open = s.indexOf('(');
    if (open < 0) return '<b>' + esc(s) + '</b>';
    var head = s.slice(0, open), rest = s.slice(open), ret = '';
    var arrow = rest.lastIndexOf('->');
    if (arrow > -1) {
      ret = rest.slice(arrow + 2).trim();
      rest = rest.slice(0, arrow).trim();
    }
    var dot = head.lastIndexOf('.');
    var pre = dot > -1 ? head.slice(0, dot + 1) : '';
    var nm = dot > -1 ? head.slice(dot + 1) : head;
    return '<s>' + esc(pre) + '</s><b>' + esc(nm) + '</b><s>' + esc(rest) + '</s>' +
           (ret ? ' <s>&rarr;</s> <u>' + esc(ret) + '</u>' : '');
  }

  function fnHTML(ns, fn) {
    var id = ns.ns + '.' + fn.n;
    var h = '<div class="lua-fn" id="' + esc(id) + '">';
    h += '<code class="lua-sig">' + sigHTML(fn) + '</code>';
    if (fn.d) h += '<div class="lua-fd">' + esc(fn.d) + '</div>';
    h += '<div class="lua-meta">';
    if (state.source === 'natives') {
      h += '<span class="lua-badge l-native">native</span>';
      if (fn.h) h += '<span>' + esc(fn.h) + '</span>';
    } else {
      h += '<span class="lua-badge l-' + layerKey(fn.l) + '">' + esc(fn.l || 'n/a') + '</span>';
      if (fn.src) h += '<span>' + esc(fn.src) + '</span>';
    }
    h += '<a class="lua-link" href="#' + esc(id) + '" title="Link to this function">#</a>';
    h += '</div></div>';
    return h;
  }

  /* ---------- rendering ---------- */

  function renderTabs() {
    var nCount = natives ? natives.stats.callables : 6471;
    tabs.innerHTML =
      '<button class="lua-tab' + (state.source === 'api' ? ' on' : '') + '" data-src="api">' +
        'Nenyoo API <em>' + API.stats.callables + '</em></button>' +
      '<button class="lua-tab' + (state.source === 'natives' ? ' on' : '') + '" data-src="natives">' +
        'GTA Natives <em>' + nCount + '</em></button>';
  }

  function renderLayers() {
    if (state.source === 'natives') { bar.innerHTML = ''; bar.hidden = true; return; }
    bar.hidden = false;
    var defs = [['', 'All'], ['engine', 'Engine'], ['foundation', 'Foundation'], ['stand', 'Stand']];
    var tally = { '': 0 };
    for (var i = 0; i < API.namespaces.length; i++) {
      var fns = API.namespaces[i].fns;
      for (var f = 0; f < fns.length; f++) {
        tally[''] += 1;
        var k = layerKey(fns[f].l);
        tally[k] = (tally[k] || 0) + 1;
      }
    }
    var html = '';
    for (var d = 0; d < defs.length; d++) {
      html += '<button class="lua-lay' + (state.layer === defs[d][0] ? ' on' : '') +
              '" data-layer="' + defs[d][0] + '">' + defs[d][1] +
              ' <em>' + (tally[defs[d][0]] || 0) + '</em></button>';
    }
    bar.innerHTML = html;
  }

  function renderSide() {
    var key = state.source + '|' + state.layer;
    if (key === state.sideKey && side.querySelector('.lua-nsbtn')) {
      // only the highlight can have changed
      var btns = side.querySelectorAll('.lua-nsbtn');
      for (var b = 0; b < btns.length; b++) {
        btns[b].classList.toggle('on', btns[b].getAttribute('data-ns') === state.ns);
      }
      return;
    }
    state.sideKey = key;

    var d = model();
    if (!d) { side.innerHTML = ''; return; }
    var groups = d.groups || ['GTA natives'];
    var html = '', valid = null, isNs = false;

    for (var g = 0; g < groups.length; g++) {
      var rows = '';
      for (var i = 0; i < d.namespaces.length; i++) {
        var n = d.namespaces[i];
        if ((n.group || 'GTA natives') !== groups[g]) continue;
        var shown = 0;
        for (var f = 0; f < n.fns.length; f++) if (passesLayer(n.fns[f])) shown++;
        if (!shown) continue;
        if (valid === null) valid = n.ns;
        if (n.ns === state.ns) isNs = true;
        rows += '<button class="lua-nsbtn' + (n.ns === state.ns ? ' on' : '') +
                '" data-ns="' + esc(n.ns) + '">' + esc(n.ns) + '<i>' + shown + '</i></button>';
      }
      if (rows) html += '<div class="lua-grp">' + esc(groups[g]) + '</div>' + rows;
    }
    side.innerHTML = html || '<div class="lua-grp">No namespaces</div>';
    if (!isNs && valid) {           // current namespace hidden by the filter
      state.ns = valid;
      state.sideKey = '';
      renderSide();
    }
  }

  function renderResults() {
    var d = model();
    if (!d) return;
    indexOnce(d);

    var q = state.q.trim().toLowerCase();
    var html = '', shown = 0, total = 0, i, f, n, fn;

    if (q) {
      for (i = 0; i < d.namespaces.length; i++) {
        n = d.namespaces[i];
        var rows = '';
        for (f = 0; f < n.fns.length; f++) {
          fn = n.fns[f];
          if (!passesLayer(fn) || fn._k.indexOf(q) < 0) continue;
          total++;
          if (shown < MAX_HITS) { rows += fnHTML(n, fn); shown++; }
        }
        if (rows) html += '<div class="lua-hit">' + esc(n.ns) + '</div>' + rows;
      }
      out.innerHTML = html ||
        '<div class="lua-state">Nothing matches &ldquo;' + esc(state.q) + '&rdquo;.</div>';
      count.textContent = total
        ? (shown < total ? 'Showing ' + shown + ' of ' + total + ' matches — narrow the search'
                         : total + ' match' + (total === 1 ? '' : 'es'))
        : '';
      return;
    }

    n = nsOf(state.ns);
    if (!n) { out.innerHTML = '<div class="lua-state">Pick a namespace.</div>'; return; }

    html += '<div class="lua-nshead"><h2>' + esc(n.ns) + '</h2>';
    if (n.desc) html += '<p>' + esc(n.desc) + '</p>';
    html += '<div class="lua-tags"><span class="lua-tag">' + esc(n.group || 'GTA natives') + '</span>';
    if (n.thread === 'render') html += '<span class="lua-tag t-render">Render thread</span>';
    if (n.thread === 'script') html += '<span class="lua-tag t-script">Script thread</span>';
    if (state.source === 'natives') html += '<span class="lua-tag t-script">Script thread only</span>';
    html += '</div></div>';

    var list = [];
    for (f = 0; f < n.fns.length; f++) if (passesLayer(n.fns[f])) list.push(n.fns[f]);

    var cap = state.expand ? list.length : Math.min(CHUNK, list.length);
    for (f = 0; f < cap; f++) html += fnHTML(n, list[f]);
    if (cap < list.length) {
      html += '<button class="lua-more" id="luaMore">Show all ' + list.length +
              ' in ' + esc(n.ns) + '</button>';
    }

    out.innerHTML = list.length ? html
      : html + '<div class="lua-state">Nothing here matches that filter.</div>';
    count.textContent = list.length + ' callable' + (list.length === 1 ? '' : 's') +
                        ' in ' + n.ns + (cap < list.length ? ' — showing ' + cap : '');
  }

  function render() { renderSide(); renderResults(); }

  function updateFoot() {
    var a = API.stats || {};
    var t = (a.callables || 0) + ' API callables · ' + (a.namespaces || 0) + ' namespaces';
    if (natives) t += ' · ' + natives.stats.callables + ' GTA natives';
    src.textContent = t + ' · generated from the build';
  }

  /* ---------- lazy natives ---------- */

  function loadNatives(then) {
    if (natives) { then(); return; }
    if (nativesLoading) return;
    nativesLoading = true;
    out.innerHTML = '<div class="lua-state">Loading the native list…</div>';
    var s = document.createElement('script');
    s.src = NATIVES_URL;
    s.onload = function () {
      nativesLoading = false;
      natives = window.NENYOO_LUA_NATIVES || null;
      if (!natives) {
        out.innerHTML = '<div class="lua-state">The native list could not be loaded.</div>';
        return;
      }
      natives.groups = ['GTA natives'];
      state.ns = natives.namespaces[0].ns;
      state.sideKey = '';
      renderTabs();
      updateFoot();
      then();
    };
    s.onerror = function () {
      nativesLoading = false;
      out.innerHTML = '<div class="lua-state">The native list could not be loaded.</div>';
    };
    document.head.appendChild(s);
  }

  function setSource(name) {
    if (state.source === name) return;
    state.source = name;
    state.q = '';
    state.expand = false;
    state.sideKey = '';
    search.value = '';
    clear.hidden = true;
    search.placeholder = name === 'natives'
      ? 'Search 6,471 natives… (SET_ENTITY_COORDS, 0x06843DA7)'
      : 'Search every function… (draw.rect, toggle, scan, yield)';
    renderTabs();
    renderLayers();
    if (name === 'natives') {
      loadNatives(render);
    } else {
      state.ns = defaultNs();
      render();
    }
  }

  function defaultNs() {
    var prefer = ['menu', 'draw', 'text', 'script'];
    for (var p = 0; p < prefer.length; p++) {
      for (var i = 0; i < API.namespaces.length; i++) {
        if (API.namespaces[i].ns === prefer[p]) return prefer[p];
      }
    }
    for (var j = 0; j < API.namespaces.length; j++) {
      if (API.namespaces[j].ns.charAt(0) !== '_') return API.namespaces[j].ns;
    }
    return API.namespaces[0].ns;
  }

  /* ---------- deep links ---------- */

  function openHash() {
    var h = decodeURIComponent((location.hash || '').replace(/^#/, ''));
    if (!h) return false;
    var nsName = h.indexOf('.') > -1 ? h.slice(0, h.indexOf('.')) : h;
    if (!nsOf(nsName)) return false;
    state.ns = nsName;
    state.q = '';
    state.expand = true;      // a deep link must reach rows past the cap
    search.value = '';
    clear.hidden = true;
    render();
    if (h.indexOf('.') > -1) {
      var el = document.getElementById(h);
      if (el) el.scrollIntoView({ block: 'center' });
    }
    return true;
  }

  /* ---------- events ---------- */

  tabs.addEventListener('click', function (e) {
    var b = e.target.closest ? e.target.closest('.lua-tab') : null;
    if (b) setSource(b.getAttribute('data-src'));
  });

  side.addEventListener('click', function (e) {
    var b = e.target.closest ? e.target.closest('.lua-nsbtn') : null;
    if (!b) return;
    state.ns = b.getAttribute('data-ns');
    state.q = '';
    state.expand = false;
    search.value = '';
    clear.hidden = true;
    render();
    out.scrollIntoView({ block: 'start', behavior: 'smooth' });
  });

  bar.addEventListener('click', function (e) {
    var b = e.target.closest ? e.target.closest('.lua-lay') : null;
    if (!b) return;
    state.layer = b.getAttribute('data-layer');
    state.expand = false;
    state.sideKey = '';
    renderLayers();
    render();
  });

  out.addEventListener('click', function (e) {
    if (e.target && e.target.id === 'luaMore') {
      state.expand = true;
      renderResults();
    }
  });

  var timer;
  search.addEventListener('input', function () {
    clear.hidden = !search.value;
    clearTimeout(timer);
    timer = setTimeout(function () {
      state.q = search.value;
      renderResults();
    }, 120);
  });

  clear.addEventListener('click', function () {
    search.value = '';
    state.q = '';
    clear.hidden = true;
    search.focus();
    renderResults();
  });

  window.addEventListener('hashchange', openHash);

  /* ---------- boot ---------- */

  state.ns = defaultNs();
  renderTabs();
  renderLayers();
  if (!openHash()) render();
  updateFoot();
})();
